### ISSUE TITLE
cannot download

### ISSUE THREAD

**Issue by yuchengchao** [jxfeb/Generative_QA#1]
the download link cannot use!

**Comment by jxfeb** [comment]
Sorry, our servers at Hong Kong have some problem with network connection
to mainland China. We are trying to fix it ASAP.

Xin

**Comment by liyi193328** [comment]
can't download yet?

**Comment by jxfeb** [comment]
The original IP address is blocked so we change to use another one. It should be OK now.

**Comment by liyi193328** [comment]
@jxfeb works now, thanks.

**Comment by jamesunnc** [comment]
Excuse me, would I have access to your codebase?

**Comment by 429765417** [comment]
why i can't download the corpus?  does it work?

**Comment by 429765417** [comment]
@jxfeb ,

**Comment by jxfeb** [comment]
Updated.
